# Generated by Django 3.2.11 on 2022-02-18 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0016_party_rehearsal_dinner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='is_attending',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='party',
            name='is_attending',
            field=models.BooleanField(null=True),
        ),
    ]
