# Generated by Django 3.2.11 on 2022-02-25 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0017_auto_20220218_1458'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedGuestList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_list_file', models.FileField(upload_to='guest-list/%Y/%m/%d')),
            ],
            options={
                'verbose_name': 'Guest List CSV',
            },
        ),
    ]
