# Generated by Django 3.2.11 on 2022-02-25 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0018_uploadedguestlist'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='party',
            options={'verbose_name_plural': 'Parties'},
        ),
    ]
