# Generated by Django 3.2.11 on 2022-02-26 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0019_alter_party_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guest',
            old_name='party',
            new_name='party_name',
        ),
    ]
