# Generated by Django 3.2.11 on 2022-02-26 03:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0020_rename_party_guest_party_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='arrival_dates',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='guest',
            name='caboose_farm',
            field=models.BooleanField(default=False),
        ),
    ]
