# Generated by Django 3.2.11 on 2022-02-26 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0021_auto_20220225_2228'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guest',
            old_name='arrival_dates',
            new_name='arrival_date',
        ),
    ]
