# Generated by Django 3.2.11 on 2022-02-26 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0023_alter_party_is_invited'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='caboose_farm',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
