# Generated by Django 3.2.11 on 2022-02-26 23:41

from django.db import migrations, models
import guests.models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0025_guest_guest_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='guest_code',
            field=models.PositiveIntegerField(default=guests.models.generate_code),
        ),
    ]
