# Generated by Django 3.2.11 on 2022-03-09 03:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0026_alter_guest_guest_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='arrival_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
    ]
