# Generated by Django 3.2.11 on 2022-03-27 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0028_alter_guest_arrival_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='caboose_farm',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
