# Generated by Django 3.2.11 on 2022-03-28 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0029_alter_guest_caboose_farm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='meal',
            field=models.CharField(blank=True, choices=[('beef', 'braised beef shortrib'), ('fish', 'salmon'), ('vegan', 'vegan')], max_length=20, null=True),
        ),
    ]
