# Generated by Django 3.2.19 on 2023-08-06 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0030_alter_guest_meal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='party',
            name='type',
        ),
    ]
