# Generated by Django 3.2.19 on 2023-08-07 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0017_auto_20220807_2143'),
        ('guests', '0031_remove_party_type'),
    ]

    operations = [
    ]
