# Generated by Django 3.2.19 on 2023-08-07 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0032_merge_0017_auto_20220807_2143_0031_remove_party_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='is_attending',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='party',
            name='is_attending',
            field=models.BooleanField(null=True),
        ),
    ]
